import {
  type BeanId,
  type FlavourId,
  type FormId,
  type QualityId,
  type SpiritTags,
  type ZodiacId,
} from "./zodiac";
import type { RitualVariant } from "./fortune";
import { useStore } from "../store";
import spiritTagsJson from "../data/generated/spirit-tags.json";

// Generated by scripts/generate-spirit-tags.py via build-content.mjs. Imported
// synchronously (~360 small records) so scoring can resolve a zodiac's tags
// without async access or a persisted snapshot.
const SPIRIT_TAGS = spiritTagsJson as Record<ZodiacId, SpiritTags>;

// Spirit rings are the radar-chart point orderings, distinct from the calendar
// orderings (FLAVOUR_ORDER, FORM_ORDER, BEAN_ORDER) in lib/zodiac. They drive
// the order attributes appear around each chart; scoring no longer reads
// adjacency, so reordering only changes layout, not the numbers.
export const SPIRIT_FLAVOUR_RING: FlavourId[] = [
  "umami",
  "bitter",
  "sour",
  "sweet",
  "spicy",
];

export const SPIRIT_FORM_RING: FormId[] = [
  "boiled",
  "dried",
  "fermented",
  "smoked",
  "roasted",
  "fried",
];

export const SPIRIT_BEAN_RING: BeanId[] = [
  "navy",
  "black",
  "cannellini",
  "edamame",
  "fava",
  "green",
  "kidney",
  "pinto",
  "adzuki",
  "chickpea",
  "mung",
  "butter",
];

// The scoring model is asymmetric in *direction* but symmetric in *shape*:
// Accept is the strong signal and only ever adds; Resist only ever subtracts.
// Which of the zodiac's two poles a choice moves depends on the tier:
//   - "good" tiers (heirloom/market/garden) express the trait, so they move the
//     friendly pole: the zodiac's own slug + friendlyBeans + friendlyForm.
//   - "bad" tiers (stale/rotten) express the trait's opposite, so they move the
//     anti pole: antiTriple + antiBeans + antiForm.
// Each pole scores identically — a `triple` delta on that pole's flavour/form/
// bean and a `soft` delta on its 2 beans + 1 form — so the anti pole mirrors the
// friendly one rather than being a weaker special case. Because antiTriple
// carries a flavour, bad tiers move the flavour ring too. Both magnitudes are
// full (un-halved) across beans, flavour, and form.
type ScoreRule = {
  triple: number;
  soft: number;
  pole: "friendly" | "anti";
};

const ACCEPT_RULES: Record<QualityId, ScoreRule> = {
  heirloom: { triple: +4, soft: +2, pole: "friendly" },
  market: { triple: +3, soft: +1, pole: "friendly" },
  garden: { triple: +2, soft: +1, pole: "friendly" },
  stale: { triple: +2, soft: 0, pole: "anti" },
  rotten: { triple: +2, soft: +1, pole: "anti" },
};

const RESIST_RULES: Record<QualityId, ScoreRule> = {
  heirloom: { triple: -1, soft: 0, pole: "friendly" },
  market: { triple: -1, soft: -1, pole: "friendly" },
  garden: { triple: -2, soft: -1, pole: "friendly" },
  stale: { triple: -1, soft: -1, pole: "anti" },
  rotten: { triple: -1, soft: 0, pole: "anti" },
};

export const SPIRIT_DIFF_THRESHOLD = 10;

export interface SpiritBeanScores {
  flavourValues: number[];
  formValues: number[];
  beanValues: number[];
  flavourHighlight: number;
  formHighlight: number;
  beanHighlight: number;
  claimedFlavourIdx: number;
  claimedFormIdx: number;
  claimedBeanIdx: number;
}

export function computeSpiritBeanScores(
  claimedSlug: ZodiacId,
  cutoffDateStr?: string,
): SpiritBeanScores {
  const [claimedFlavourId, claimedFormId, claimedBeanId] = claimedSlug.split(
    "-",
  ) as [FlavourId, FormId, BeanId];

  const flavourScores = Object.fromEntries(
    SPIRIT_FLAVOUR_RING.map((id) => [id, 12]),
  );
  const formScores = Object.fromEntries(SPIRIT_FORM_RING.map((id) => [id, 12]));
  const beanScores = Object.fromEntries(SPIRIT_BEAN_RING.map((id) => [id, 12]));

  flavourScores[claimedFlavourId] += 12;
  formScores[claimedFormId] += 12;
  beanScores[claimedBeanId] += 12;

  const history = cutoffDateStr
    ? useStore.getState().fortuneHistory.filter((e) => e.date <= cutoffDateStr)
    : useStore.getState().fortuneHistory;
  for (const entry of history) {
    const s = entry.score ?? 0;
    if (s === 0) continue;
    const accepted = s > 0;

    // Tags are looked up by zodiacId, never read from entry.spiritTags: they're
    // a pure function of the zodiac, so the persisted snapshot on old entries
    // would just be a stale copy in an outdated shape. Legacy entries therefore
    // score correctly without migration. (Trade-off: regenerating tags
    // retroactively re-scores history.)
    const tags = SPIRIT_TAGS[entry.zodiacId];
    if (!tags) continue;

    const rule = (accepted ? ACCEPT_RULES : RESIST_RULES)[entry.qualityId];

    // Rorschach answers count half — 50% of a normal score, rounded toward the
    // choice's direction, so a non-zero rule always keeps at least a minimal
    // nudge in its own sign. Applied identically to the triple and soft deltas.
    const half = entry.variant === "rorschach";
    const scale = (n: number) =>
      half ? Math.sign(n) * Math.ceil(Math.abs(n) / 2) : n;

    // Pick the pole this tier moves. The friendly pole is the fortune's own
    // slug; the anti pole is its shadow (antiTriple). Both are real zodiac
    // slugs, so the triple pass is identical for either.
    const friendly = rule.pole === "friendly";
    const poleSlug = friendly ? entry.zodiacId : tags.antiTriple;
    const poleBeans = friendly ? tags.friendlyBeans : tags.antiBeans;
    const poleForm = friendly ? tags.friendlyForm : tags.antiForm;

    // Triple pass: the pole's own flavour/form/bean.
    const [f, frm, b] = poleSlug.split("-") as [FlavourId, FormId, BeanId];
    const triple = scale(rule.triple);
    flavourScores[f] += triple;
    formScores[frm] += triple;
    beanScores[b] += triple;

    // Soft pass: the pole's entourage — 2 beans + 1 form, at full magnitude.
    const soft = scale(rule.soft);
    if (soft !== 0) {
      for (const id of poleBeans) beanScores[id] += soft;
      formScores[poleForm] += soft;
    }
  }

  const flavourValues = SPIRIT_FLAVOUR_RING.map((id) =>
    Math.max(0, flavourScores[id]),
  );
  const formValues = SPIRIT_FORM_RING.map((id) => Math.max(0, formScores[id]));
  const beanValues = SPIRIT_BEAN_RING.map((id) => Math.max(0, beanScores[id]));

  const claimedFlavourIdx = SPIRIT_FLAVOUR_RING.indexOf(claimedFlavourId);
  const claimedFormIdx = SPIRIT_FORM_RING.indexOf(claimedFormId);
  const claimedBeanIdx = SPIRIT_BEAN_RING.indexOf(claimedBeanId);

  const pickHighlight = (values: number[], claimedIdx: number) => {
    const max = Math.max(...values);
    return values[claimedIdx] === max ? claimedIdx : values.indexOf(max);
  };

  return {
    flavourValues,
    formValues,
    beanValues,
    flavourHighlight: pickHighlight(flavourValues, claimedFlavourIdx),
    formHighlight: pickHighlight(formValues, claimedFormIdx),
    beanHighlight: pickHighlight(beanValues, claimedBeanIdx),
    claimedFlavourIdx,
    claimedFormIdx,
    claimedBeanIdx,
  };
}

export function getSpiritZodiacId(scores: SpiritBeanScores): ZodiacId {
  return `${SPIRIT_FLAVOUR_RING[scores.flavourHighlight]}-${SPIRIT_FORM_RING[scores.formHighlight]}-${SPIRIT_BEAN_RING[scores.beanHighlight]}` as ZodiacId;
}

export function getSpiritDiff(scores: SpiritBeanScores): number {
  return (
    Math.max(...scores.flavourValues) -
    scores.flavourValues[scores.claimedFlavourIdx] +
    (Math.max(...scores.formValues) -
      scores.formValues[scores.claimedFormIdx]) +
    (Math.max(...scores.beanValues) - scores.beanValues[scores.claimedBeanIdx])
  );
}

const ALIGNMENT_TEXTS = [
  // 0–9: mild
  "Your body and spirit align.",
  "A seed contains everything — including its opposite.",
  "Something beneath the surface has begun to want.",
  "The self is not entirely still.",
  "Change asks quietly before it enters.",
  "A small door has opened.",
  "What you are and what you are becoming have not yet met.",
  "The self leans — barely, but leaning is how it starts.",
  "A pull exists in you that has no name yet.",
  "You are faithful to your nature, though it has begun to wander.",
  // 10–19: moderate
  "Change has stopped asking.",
  "What you were and what you are no longer agree.",
  "You have grown in directions your origin did not anticipate.",
  "The self you were given and the self you made are in negotiation.",
  "You are becoming something your beginning did not plan for.",
  "The original self persists — but quietly.",
  "Two truths live in you now, and both are real.",
  "What shaped you first no longer shapes you most.",
  "You have been unmade and remade — not all at once, but steadily.",
  "The origin remains, but it no longer governs.",
  // 20–29: extreme
  "You have outgrown the self you were handed.",
  "What you were is now a reference point, not a home.",
  "Nothing anchors you to the beginning anymore.",
  "The self that was born and the self that lives have parted ways.",
  "You are no longer what you were — and what you were knows it.",
  "Change does not always return what it borrows.",
  "What you've become cannot be traced back to where you began.",
  "The beginning would not recognize the end.",
  "The river has forgotten it was ever rain.",
  "Your origin is no longer behind you — it is simply gone.",
];

export function getAlignmentText(spiritDiff: number): string {
  return ALIGNMENT_TEXTS[Math.min(spiritDiff, ALIGNMENT_TEXTS.length - 1)];
}

export type BeanstalkNode = {
  kind: "fortune";
  date: string;
  scores: SpiritBeanScores;
  spiritZodiacId: ZodiacId;
  fortuneZodiacId: ZodiacId;
  qualityId: QualityId;
  facetTitle: string;
  facetText: string;
  score: number;
  text: string | null;
  variant: RitualVariant;
  question: string | null;
  answeredQuality: QualityId | null;
  answerText: string | null;
  rorschachImage: string | null;
  rorschachText: string | null;
};

export function buildBeanstalkNodes(claimedSlug: ZodiacId): BeanstalkNode[] {
  const history = useStore
    .getState()
    .fortuneHistory.sort((a, b) => (a.date < b.date ? -1 : 1));

  if (history.length === 0) return [];

  const fortuneNodes: BeanstalkNode[] = history.map((entry) => {
    const scores = computeSpiritBeanScores(claimedSlug, entry.date);
    const spiritZodiacId = getSpiritZodiacId(scores);
    return {
      kind: "fortune",
      date: entry.date,
      scores,
      spiritZodiacId,
      fortuneZodiacId: entry.zodiacId,
      qualityId: entry.qualityId,
      facetTitle: entry.facetTitle,
      facetText: entry.facetText,
      score: entry.score || 0,
      text: entry.text ?? null,
      variant: entry.variant ?? "facet",
      question: entry.question ?? null,
      answeredQuality: entry.answeredQuality ?? null,
      answerText: entry.answerText ?? null,
      rorschachImage: entry.rorschachImage ?? null,
      rorschachText: entry.rorschachText ?? null,
    };
  });

  return fortuneNodes;
}
