export const BeanIds = {
  Adzuki: "adzuki",
  Black: "black",
  Butter: "butter",
  Cannellini: "cannellini",
  Chickpea: "chickpea",
  Edamame: "edamame",
  Fava: "fava",
  Green: "green",
  Kidney: "kidney",
  Mung: "mung",
  Navy: "navy",
  Pinto: "pinto",
} as const;
export type BeanId = (typeof BeanIds)[keyof typeof BeanIds];

export const FlavourIds = {
  Bitter: "bitter",
  Sour: "sour",
  Spicy: "spicy",
  Sweet: "sweet",
  Umami: "umami",
} as const;
export type FlavourId = (typeof FlavourIds)[keyof typeof FlavourIds];

export const FormIds = {
  Boiled: "boiled",
  Dried: "dried",
  Fermented: "fermented",
  Fried: "fried",
  Roasted: "roasted",
  Smoked: "smoked",
} as const;
export type FormId = (typeof FormIds)[keyof typeof FormIds];

export const QualityIds = {
  Rotten: "rotten",
  Stale: "stale",
  Garden: "garden",
  Market: "market",
  Heirloom: "heirloom",
} as const;
export type QualityId = (typeof QualityIds)[keyof typeof QualityIds];

export type ZodiacId = `${FlavourId}-${FormId}-${BeanId}`;
export type PreparationId = `${FlavourId}-${FormId}`;

// Spirit tags steer the Beanstalk's scoring pass. The model is symmetric: each
// zodiac has a friendly pole (its own slug + friendlyBeans + friendlyForm) and
// an anti pole (antiTriple + antiBeans + antiForm), each covering 3 distinct
// beans and 2 distinct forms. `antiTriple` is the zodiac's shadow — itself a
// real zodiac slug — so the anti pole gets flavour movement through its triple,
// exactly as the friendly pole does.
//
// Trait-positive tiers (Most/High/Mid) move the friendly pole; anti-trait tiers
// (Low/Least) move the anti pole. Accept lifts the active pole, Resist lowers
// it. Generated by scripts/generate-spirit-tags.py; looked up by zodiacId at
// score time (never read from persisted history). See lib/spiritBean.
export type SpiritTags = {
  friendlyBeans: BeanId[];
  antiBeans: BeanId[];
  antiTriple: ZodiacId;
  friendlyForm: FormId;
  antiForm: FormId;
};

// Each axis carries its own trait vocabulary — beans take motive words, flavours
// take affect words, forms take metabolism words — so a full triple reads as
// three non-overlapping descriptions rather than three shades of the same one.
export type BeanSchema = {
  name: string;
  slug: BeanId;
  /** The motive in two words — "The Healer", "The Steward". */
  role: string;
  tagline: string;
  positiveTraits: string[];
  negativeTraits: string[];
  imageFile: string;
};

export type FlavourSchema = {
  name: string;
  slug: FlavourId;
  tagline: string;
  positiveTraits: string[];
  negativeTraits: string[];
};

export type FormSchema = {
  name: string;
  slug: FormId;
  tagline: string;
  positiveTraits: string[];
  negativeTraits: string[];
};

/** A Flavour × Form pairing — what the affect and the metabolism produce together. */
export type PreparationSchema = {
  name: string;
  slug: PreparationId;
  flavour: FlavourId;
  form: FormId;
  positiveTraits: string[];
  negativeTraits: string[];
};

export type ZodiacSchema = {
  slug: string;
  bean: string;
  flavour: string;
  form: string;
  trait: string;
  inverse: string;
  excess: string;
  dish: string;
  quote: string;
  seasonalFortune: string;
  facetLeastTitle: string;
  facetLeast: string;
  facetLowTitle: string;
  facetLow: string;
  facetMidTitle: string;
  facetMid: string;
  facetHighTitle: string;
  facetHigh: string;
  facetMostTitle: string;
  facetMost: string;
  friendlyBeans: BeanId[];
  antiBeans: BeanId[];
  antiTriple: ZodiacId;
  friendlyForm: FormId;
  antiForm: FormId;
  fortuneLeast: string;
  fortuneLeast2: string;
  fortuneLow: string;
  fortuneLow2: string;
  fortuneMid: string;
  fortuneMid2: string;
  fortuneHigh: string;
  fortuneHigh2: string;
  fortuneMost: string;
  fortuneMost2: string;
  question: string;
  answerMost: string;
  answerHigh: string;
  answerMid: string;
  answerLow: string;
  answerLeast: string;
  rorschachMost: string;
  rorschachHigh: string;
  rorschachMid: string;
  rorschachLow: string;
  rorschachLeast: string;
};

export type Bean = BeanSchema & { content: string };
export type Flavour = FlavourSchema & { content: string };
export type Form = FormSchema & { content: string };
export type Preparation = PreparationSchema & { content: string };
export type Zodiac = ZodiacSchema & { content: string };

export type ZodiacMetadata = {
  zodiacId: ZodiacId;
  beanId: BeanId;
  flavourId: FlavourId;
  formId: FormId;
  startDate: Date;
  endDate: Date;
};
