import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import matter from "gray-matter";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

function readCollection(name) {
  const dir = resolve(root, `src/content/${name}`);
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md") && !/^[A-Z]/.test(f))
    .map((f) => {
      const { data, content } = matter(readFileSync(resolve(dir, f), "utf8"));
      return { id: f.replace(/\.md$/, ""), data, content: content.trim() };
    });
}

function writeJson(path, value) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(value, null, 2));
}

// Beans
const beans = readCollection("beans");
const beansRecord = Object.fromEntries(
  beans.map(({ id, data, content }) => [id, { ...data, content }]),
);
writeJson(resolve(root, "src/data/generated/beans.json"), beansRecord);

// Flavours
const flavours = readCollection("flavours");
const flavoursRecord = Object.fromEntries(
  flavours.map(({ id, data, content }) => [id, { ...data, content }]),
);
writeJson(resolve(root, "src/data/generated/flavours.json"), flavoursRecord);

// Forms
const forms = readCollection("forms");
const formsRecord = Object.fromEntries(
  forms.map(({ id, data, content }) => [id, { ...data, content }]),
);
writeJson(resolve(root, "src/data/generated/forms.json"), formsRecord);

// Spirit tags (see SPIRIT_TAGS.md). Generated by scripts/generate-spirit-tags.py.
// friendly* align with the trait, anti* with its opposite; never the zodiac's
// own bean/form. Flavours are deliberately untagged. Beans come in pairs; form
// is a single id.
const BEAN_IDS = new Set([
  "adzuki", "black", "butter", "cannellini", "chickpea", "edamame",
  "fava", "green", "kidney", "mung", "navy", "pinto",
]);
const FORM_IDS = new Set(["boiled", "dried", "fermented", "fried", "roasted", "smoked"]);

function validateSpiritTags(id, data, own) {
  for (const field of ["friendlyBeans", "antiBeans"]) {
    const tags = data[field];
    if (!Array.isArray(tags) || tags.length !== 2) {
      throw new Error(`${id}: ${field} must be a list of exactly 2 beans`);
    }
    for (const tag of tags) {
      if (!BEAN_IDS.has(tag)) throw new Error(`${id}: ${field} has invalid bean "${tag}"`);
      if (tag === own.bean) throw new Error(`${id}: ${field} must not include the zodiac's own bean`);
    }
  }
  for (const field of ["friendlyForm", "antiForm"]) {
    const v = data[field];
    if (typeof v !== "string" || !FORM_IDS.has(v)) {
      throw new Error(`${id}: ${field} must be a valid form id, got "${v}"`);
    }
    if (v === own.form) throw new Error(`${id}: ${field} must not be the zodiac's own form`);
  }
}

// Zodiacs — one JSON per slug, plus also copy to public/api/zodiacs/ for dev server
const zodiacs = readCollection("zodiacs");
const zodiacDir = resolve(root, "src/data/generated/zodiacs");
const publicDir = resolve(root, "public/api/zodiacs");
mkdirSync(zodiacDir, { recursive: true });
mkdirSync(publicDir, { recursive: true });

for (const { id, data, content } of zodiacs) {
  validateSpiritTags(id, data, { bean: data.bean, form: data.form });
  const payload = JSON.stringify({ ...data, content });
  writeFileSync(resolve(zodiacDir, `${id}.json`), payload);
  writeFileSync(resolve(publicDir, `${id}.json`), payload);
}

console.log(
  `Built ${beans.length} beans, ${flavours.length} flavours, ${forms.length} forms, ${zodiacs.length} zodiacs`,
);

await import("./build-rorschach.mjs");
