import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import matter from "gray-matter";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

function readCollection(name) {
  const dir = resolve(root, `src/content/${name}`);
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md") && !/^[A-Z]/.test(f))
    .map((f) => {
      const { data, content } = matter(readFileSync(resolve(dir, f), "utf8"));
      return { id: f.replace(/\.md$/, ""), data, content: content.trim() };
    });
}

function writeJson(path, value) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(value, null, 2));
}

// Beans
const beans = readCollection("beans");
const beansRecord = Object.fromEntries(
  beans.map(({ id, data, content }) => [id, { ...data, content }]),
);
writeJson(resolve(root, "src/data/generated/beans.json"), beansRecord);

// Flavours
const flavours = readCollection("flavours");
const flavoursRecord = Object.fromEntries(
  flavours.map(({ id, data, content }) => [id, { ...data, content }]),
);
writeJson(resolve(root, "src/data/generated/flavours.json"), flavoursRecord);

// Forms
const forms = readCollection("forms");
const formsRecord = Object.fromEntries(
  forms.map(({ id, data, content }) => [id, { ...data, content }]),
);
writeJson(resolve(root, "src/data/generated/forms.json"), formsRecord);

// Spirit tags (see SPIRIT_TAGS.md). Generated by scripts/generate-spirit-tags.py.
// The model is symmetric: each zodiac has a friendly pole (its own slug +
// friendlyBeans + friendlyForm) and an anti pole (antiTriple + antiBeans +
// antiForm). Never the zodiac's own bean/form/flavour; the anti-triple's
// bean/form are also barred from antiBeans/antiForm so each pole covers 3
// distinct beans and 2 distinct forms.
const BEAN_IDS = new Set([
  "adzuki", "black", "butter", "cannellini", "chickpea", "edamame",
  "fava", "green", "kidney", "mung", "navy", "pinto",
]);
const FORM_IDS = new Set(["boiled", "dried", "fermented", "fried", "roasted", "smoked"]);
const FLAVOUR_IDS = new Set(["umami", "bitter", "sour", "sweet", "spicy"]);

function validateSpiritTags(id, data, own) {
  for (const field of ["friendlyBeans", "antiBeans"]) {
    const tags = data[field];
    if (!Array.isArray(tags) || tags.length !== 2) {
      throw new Error(`${id}: ${field} must be a list of exactly 2 beans`);
    }
    for (const tag of tags) {
      if (!BEAN_IDS.has(tag)) throw new Error(`${id}: ${field} has invalid bean "${tag}"`);
      if (tag === own.bean) throw new Error(`${id}: ${field} must not include the zodiac's own bean`);
    }
  }
  for (const field of ["friendlyForm", "antiForm"]) {
    const v = data[field];
    if (typeof v !== "string" || !FORM_IDS.has(v)) {
      throw new Error(`${id}: ${field} must be a valid form id, got "${v}"`);
    }
    if (v === own.form) throw new Error(`${id}: ${field} must not be the zodiac's own form`);
  }
  const parts = String(data.antiTriple ?? "").split("-");
  if (parts.length !== 3) {
    throw new Error(`${id}: antiTriple must be a {flavour}-{form}-{bean} slug, got "${data.antiTriple}"`);
  }
  const [tFlavour, tForm, tBean] = parts;
  if (!FLAVOUR_IDS.has(tFlavour)) throw new Error(`${id}: antiTriple has invalid flavour "${tFlavour}"`);
  if (!FORM_IDS.has(tForm)) throw new Error(`${id}: antiTriple has invalid form "${tForm}"`);
  if (!BEAN_IDS.has(tBean)) throw new Error(`${id}: antiTriple has invalid bean "${tBean}"`);
  if (tFlavour === own.flavour) throw new Error(`${id}: antiTriple must not use the zodiac's own flavour`);
  if (tForm === own.form) throw new Error(`${id}: antiTriple must not use the zodiac's own form`);
  if (tBean === own.bean) throw new Error(`${id}: antiTriple must not use the zodiac's own bean`);
  // Each pole must cover 3 distinct beans and 2 distinct forms.
  if (data.antiBeans.includes(tBean)) {
    throw new Error(`${id}: antiTriple's bean "${tBean}" must not also appear in antiBeans`);
  }
  if (data.antiForm === tForm) {
    throw new Error(`${id}: antiTriple's form "${tForm}" must not also be antiForm`);
  }
}

// Zodiacs — one JSON per slug, plus also copy to public/api/zodiacs/ for dev server
const zodiacs = readCollection("zodiacs");
const zodiacDir = resolve(root, "src/data/generated/zodiacs");
const publicDir = resolve(root, "public/api/zodiacs");
mkdirSync(zodiacDir, { recursive: true });
mkdirSync(publicDir, { recursive: true });

const zodiacTraits = {};
const spiritTags = {};
for (const { id, data, content } of zodiacs) {
  validateSpiritTags(id, data, { bean: data.bean, form: data.form, flavour: data.flavour });
  const payload = JSON.stringify({ ...data, content });
  writeFileSync(resolve(zodiacDir, `${id}.json`), payload);
  writeFileSync(resolve(publicDir, `${id}.json`), payload);
  zodiacTraits[id] = data.trait;
  spiritTags[id] = {
    friendlyBeans: data.friendlyBeans,
    antiBeans: data.antiBeans,
    antiTriple: data.antiTriple,
    friendlyForm: data.friendlyForm,
    antiForm: data.antiForm,
  };
}

// Flat id → spirit-tag index, imported synchronously by lib/spiritBean. The tags
// are a pure function of the zodiac, so scoring looks them up by zodiacId at
// score time rather than reading the snapshot persisted on old fortune entries —
// which means the tag model can change shape without migrating stored history.
// Trade-off: regenerating tags retroactively re-scores past entries.
writeJson(resolve(root, "src/data/generated/spirit-tags.json"), spiritTags);

// Flat id → trait index for synchronous lookups (the season-summary bridge line);
// avoids fetching a full zodiac JSON just to read one word.
writeJson(resolve(root, "src/data/generated/zodiac-traits.json"), zodiacTraits);

console.log(
  `Built ${beans.length} beans, ${flavours.length} flavours, ${forms.length} forms, ${zodiacs.length} zodiacs`,
);

await import("./build-rorschach.mjs");
