/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WheelRouteImport } from './routes/wheel'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BeanstalkRouteImport } from './routes/beanstalk'
import { Route as BeaniaryRouteImport } from './routes/beaniary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZodiacsIndexRouteImport } from './routes/zodiacs/index'
import { Route as FormsIndexRouteImport } from './routes/forms/index'
import { Route as FlavoursIndexRouteImport } from './routes/flavours/index'
import { Route as BeansIndexRouteImport } from './routes/beans/index'
import { Route as ZodiacsIdRouteImport } from './routes/zodiacs/$id'
import { Route as FormsIdRouteImport } from './routes/forms/$id'
import { Route as FlavoursIdRouteImport } from './routes/flavours/$id'
import { Route as BeansIdRouteImport } from './routes/beans/$id'

const WheelRoute = WheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BeanstalkRoute = BeanstalkRouteImport.update({
  id: '/beanstalk',
  path: '/beanstalk',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaniaryRoute = BeaniaryRouteImport.update({
  id: '/beaniary',
  path: '/beaniary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZodiacsIndexRoute = ZodiacsIndexRouteImport.update({
  id: '/zodiacs/',
  path: '/zodiacs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavoursIndexRoute = FlavoursIndexRouteImport.update({
  id: '/flavours/',
  path: '/flavours/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansIndexRoute = BeansIndexRouteImport.update({
  id: '/beans/',
  path: '/beans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZodiacsIdRoute = ZodiacsIdRouteImport.update({
  id: '/zodiacs/$id',
  path: '/zodiacs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIdRoute = FormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavoursIdRoute = FlavoursIdRouteImport.update({
  id: '/flavours/$id',
  path: '/flavours/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansIdRoute = BeansIdRouteImport.update({
  id: '/beans/$id',
  path: '/beans/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beaniary': typeof BeaniaryRoute
  '/beanstalk': typeof BeanstalkRoute
  '/calendar': typeof CalendarRoute
  '/compatibility': typeof CompatibilityRoute
  '/wheel': typeof WheelRoute
  '/beans/$id': typeof BeansIdRoute
  '/flavours/$id': typeof FlavoursIdRoute
  '/forms/$id': typeof FormsIdRoute
  '/zodiacs/$id': typeof ZodiacsIdRoute
  '/beans/': typeof BeansIndexRoute
  '/flavours/': typeof FlavoursIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/zodiacs/': typeof ZodiacsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beaniary': typeof BeaniaryRoute
  '/beanstalk': typeof BeanstalkRoute
  '/calendar': typeof CalendarRoute
  '/compatibility': typeof CompatibilityRoute
  '/wheel': typeof WheelRoute
  '/beans/$id': typeof BeansIdRoute
  '/flavours/$id': typeof FlavoursIdRoute
  '/forms/$id': typeof FormsIdRoute
  '/zodiacs/$id': typeof ZodiacsIdRoute
  '/beans': typeof BeansIndexRoute
  '/flavours': typeof FlavoursIndexRoute
  '/forms': typeof FormsIndexRoute
  '/zodiacs': typeof ZodiacsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beaniary': typeof BeaniaryRoute
  '/beanstalk': typeof BeanstalkRoute
  '/calendar': typeof CalendarRoute
  '/compatibility': typeof CompatibilityRoute
  '/wheel': typeof WheelRoute
  '/beans/$id': typeof BeansIdRoute
  '/flavours/$id': typeof FlavoursIdRoute
  '/forms/$id': typeof FormsIdRoute
  '/zodiacs/$id': typeof ZodiacsIdRoute
  '/beans/': typeof BeansIndexRoute
  '/flavours/': typeof FlavoursIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/zodiacs/': typeof ZodiacsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beaniary'
    | '/beanstalk'
    | '/calendar'
    | '/compatibility'
    | '/wheel'
    | '/beans/$id'
    | '/flavours/$id'
    | '/forms/$id'
    | '/zodiacs/$id'
    | '/beans/'
    | '/flavours/'
    | '/forms/'
    | '/zodiacs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beaniary'
    | '/beanstalk'
    | '/calendar'
    | '/compatibility'
    | '/wheel'
    | '/beans/$id'
    | '/flavours/$id'
    | '/forms/$id'
    | '/zodiacs/$id'
    | '/beans'
    | '/flavours'
    | '/forms'
    | '/zodiacs'
  id:
    | '__root__'
    | '/'
    | '/beaniary'
    | '/beanstalk'
    | '/calendar'
    | '/compatibility'
    | '/wheel'
    | '/beans/$id'
    | '/flavours/$id'
    | '/forms/$id'
    | '/zodiacs/$id'
    | '/beans/'
    | '/flavours/'
    | '/forms/'
    | '/zodiacs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeaniaryRoute: typeof BeaniaryRoute
  BeanstalkRoute: typeof BeanstalkRoute
  CalendarRoute: typeof CalendarRoute
  CompatibilityRoute: typeof CompatibilityRoute
  WheelRoute: typeof WheelRoute
  BeansIdRoute: typeof BeansIdRoute
  FlavoursIdRoute: typeof FlavoursIdRoute
  FormsIdRoute: typeof FormsIdRoute
  ZodiacsIdRoute: typeof ZodiacsIdRoute
  BeansIndexRoute: typeof BeansIndexRoute
  FlavoursIndexRoute: typeof FlavoursIndexRoute
  FormsIndexRoute: typeof FormsIndexRoute
  ZodiacsIndexRoute: typeof ZodiacsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wheel': {
      id: '/wheel'
      path: '/wheel'
      fullPath: '/wheel'
      preLoaderRoute: typeof WheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beanstalk': {
      id: '/beanstalk'
      path: '/beanstalk'
      fullPath: '/beanstalk'
      preLoaderRoute: typeof BeanstalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaniary': {
      id: '/beaniary'
      path: '/beaniary'
      fullPath: '/beaniary'
      preLoaderRoute: typeof BeaniaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zodiacs/': {
      id: '/zodiacs/'
      path: '/zodiacs'
      fullPath: '/zodiacs/'
      preLoaderRoute: typeof ZodiacsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavours/': {
      id: '/flavours/'
      path: '/flavours'
      fullPath: '/flavours/'
      preLoaderRoute: typeof FlavoursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/': {
      id: '/beans/'
      path: '/beans'
      fullPath: '/beans/'
      preLoaderRoute: typeof BeansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zodiacs/$id': {
      id: '/zodiacs/$id'
      path: '/zodiacs/$id'
      fullPath: '/zodiacs/$id'
      preLoaderRoute: typeof ZodiacsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$id': {
      id: '/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof FormsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavours/$id': {
      id: '/flavours/$id'
      path: '/flavours/$id'
      fullPath: '/flavours/$id'
      preLoaderRoute: typeof FlavoursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/$id': {
      id: '/beans/$id'
      path: '/beans/$id'
      fullPath: '/beans/$id'
      preLoaderRoute: typeof BeansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeaniaryRoute: BeaniaryRoute,
  BeanstalkRoute: BeanstalkRoute,
  CalendarRoute: CalendarRoute,
  CompatibilityRoute: CompatibilityRoute,
  WheelRoute: WheelRoute,
  BeansIdRoute: BeansIdRoute,
  FlavoursIdRoute: FlavoursIdRoute,
  FormsIdRoute: FormsIdRoute,
  ZodiacsIdRoute: ZodiacsIdRoute,
  BeansIndexRoute: BeansIndexRoute,
  FlavoursIndexRoute: FlavoursIndexRoute,
  FormsIndexRoute: FormsIndexRoute,
  ZodiacsIndexRoute: ZodiacsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
