/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WheelRouteImport } from './routes/wheel'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BeanstalkRouteImport } from './routes/beanstalk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZodiacsIndexRouteImport } from './routes/zodiacs/index'
import { Route as FormsIndexRouteImport } from './routes/forms/index'
import { Route as FlavoursIndexRouteImport } from './routes/flavours/index'
import { Route as BeansIndexRouteImport } from './routes/beans/index'
import { Route as BeaniaryIndexRouteImport } from './routes/beaniary/index'
import { Route as ZodiacsIdRouteImport } from './routes/zodiacs/$id'
import { Route as FormsIdRouteImport } from './routes/forms/$id'
import { Route as FlavoursIdRouteImport } from './routes/flavours/$id'
import { Route as BeansIdRouteImport } from './routes/beans/$id'
import { Route as BeaniaryMetRouteImport } from './routes/beaniary/met'
import { Route as BeaniaryFormsIndexRouteImport } from './routes/beaniary/forms/index'
import { Route as BeaniaryFlavoursIndexRouteImport } from './routes/beaniary/flavours/index'
import { Route as BeaniaryBeansIndexRouteImport } from './routes/beaniary/beans/index'
import { Route as BeaniaryFormsIdRouteImport } from './routes/beaniary/forms/$id'
import { Route as BeaniaryFlavoursIdRouteImport } from './routes/beaniary/flavours/$id'
import { Route as BeaniaryBeansIdRouteImport } from './routes/beaniary/beans/$id'

const WheelRoute = WheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BeanstalkRoute = BeanstalkRouteImport.update({
  id: '/beanstalk',
  path: '/beanstalk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZodiacsIndexRoute = ZodiacsIndexRouteImport.update({
  id: '/zodiacs/',
  path: '/zodiacs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavoursIndexRoute = FlavoursIndexRouteImport.update({
  id: '/flavours/',
  path: '/flavours/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansIndexRoute = BeansIndexRouteImport.update({
  id: '/beans/',
  path: '/beans/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaniaryIndexRoute = BeaniaryIndexRouteImport.update({
  id: '/beaniary/',
  path: '/beaniary/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZodiacsIdRoute = ZodiacsIdRouteImport.update({
  id: '/zodiacs/$id',
  path: '/zodiacs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIdRoute = FormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavoursIdRoute = FlavoursIdRouteImport.update({
  id: '/flavours/$id',
  path: '/flavours/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansIdRoute = BeansIdRouteImport.update({
  id: '/beans/$id',
  path: '/beans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaniaryMetRoute = BeaniaryMetRouteImport.update({
  id: '/beaniary/met',
  path: '/beaniary/met',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaniaryFormsIndexRoute = BeaniaryFormsIndexRouteImport.update({
  id: '/beaniary/forms/',
  path: '/beaniary/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaniaryFlavoursIndexRoute = BeaniaryFlavoursIndexRouteImport.update({
  id: '/beaniary/flavours/',
  path: '/beaniary/flavours/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaniaryBeansIndexRoute = BeaniaryBeansIndexRouteImport.update({
  id: '/beaniary/beans/',
  path: '/beaniary/beans/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaniaryFormsIdRoute = BeaniaryFormsIdRouteImport.update({
  id: '/beaniary/forms/$id',
  path: '/beaniary/forms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaniaryFlavoursIdRoute = BeaniaryFlavoursIdRouteImport.update({
  id: '/beaniary/flavours/$id',
  path: '/beaniary/flavours/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaniaryBeansIdRoute = BeaniaryBeansIdRouteImport.update({
  id: '/beaniary/beans/$id',
  path: '/beaniary/beans/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beanstalk': typeof BeanstalkRoute
  '/calendar': typeof CalendarRoute
  '/compatibility': typeof CompatibilityRoute
  '/wheel': typeof WheelRoute
  '/beaniary/met': typeof BeaniaryMetRoute
  '/beans/$id': typeof BeansIdRoute
  '/flavours/$id': typeof FlavoursIdRoute
  '/forms/$id': typeof FormsIdRoute
  '/zodiacs/$id': typeof ZodiacsIdRoute
  '/beaniary/': typeof BeaniaryIndexRoute
  '/beans/': typeof BeansIndexRoute
  '/flavours/': typeof FlavoursIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/zodiacs/': typeof ZodiacsIndexRoute
  '/beaniary/beans/$id': typeof BeaniaryBeansIdRoute
  '/beaniary/flavours/$id': typeof BeaniaryFlavoursIdRoute
  '/beaniary/forms/$id': typeof BeaniaryFormsIdRoute
  '/beaniary/beans/': typeof BeaniaryBeansIndexRoute
  '/beaniary/flavours/': typeof BeaniaryFlavoursIndexRoute
  '/beaniary/forms/': typeof BeaniaryFormsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beanstalk': typeof BeanstalkRoute
  '/calendar': typeof CalendarRoute
  '/compatibility': typeof CompatibilityRoute
  '/wheel': typeof WheelRoute
  '/beaniary/met': typeof BeaniaryMetRoute
  '/beans/$id': typeof BeansIdRoute
  '/flavours/$id': typeof FlavoursIdRoute
  '/forms/$id': typeof FormsIdRoute
  '/zodiacs/$id': typeof ZodiacsIdRoute
  '/beaniary': typeof BeaniaryIndexRoute
  '/beans': typeof BeansIndexRoute
  '/flavours': typeof FlavoursIndexRoute
  '/forms': typeof FormsIndexRoute
  '/zodiacs': typeof ZodiacsIndexRoute
  '/beaniary/beans/$id': typeof BeaniaryBeansIdRoute
  '/beaniary/flavours/$id': typeof BeaniaryFlavoursIdRoute
  '/beaniary/forms/$id': typeof BeaniaryFormsIdRoute
  '/beaniary/beans': typeof BeaniaryBeansIndexRoute
  '/beaniary/flavours': typeof BeaniaryFlavoursIndexRoute
  '/beaniary/forms': typeof BeaniaryFormsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beanstalk': typeof BeanstalkRoute
  '/calendar': typeof CalendarRoute
  '/compatibility': typeof CompatibilityRoute
  '/wheel': typeof WheelRoute
  '/beaniary/met': typeof BeaniaryMetRoute
  '/beans/$id': typeof BeansIdRoute
  '/flavours/$id': typeof FlavoursIdRoute
  '/forms/$id': typeof FormsIdRoute
  '/zodiacs/$id': typeof ZodiacsIdRoute
  '/beaniary/': typeof BeaniaryIndexRoute
  '/beans/': typeof BeansIndexRoute
  '/flavours/': typeof FlavoursIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/zodiacs/': typeof ZodiacsIndexRoute
  '/beaniary/beans/$id': typeof BeaniaryBeansIdRoute
  '/beaniary/flavours/$id': typeof BeaniaryFlavoursIdRoute
  '/beaniary/forms/$id': typeof BeaniaryFormsIdRoute
  '/beaniary/beans/': typeof BeaniaryBeansIndexRoute
  '/beaniary/flavours/': typeof BeaniaryFlavoursIndexRoute
  '/beaniary/forms/': typeof BeaniaryFormsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beanstalk'
    | '/calendar'
    | '/compatibility'
    | '/wheel'
    | '/beaniary/met'
    | '/beans/$id'
    | '/flavours/$id'
    | '/forms/$id'
    | '/zodiacs/$id'
    | '/beaniary/'
    | '/beans/'
    | '/flavours/'
    | '/forms/'
    | '/zodiacs/'
    | '/beaniary/beans/$id'
    | '/beaniary/flavours/$id'
    | '/beaniary/forms/$id'
    | '/beaniary/beans/'
    | '/beaniary/flavours/'
    | '/beaniary/forms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beanstalk'
    | '/calendar'
    | '/compatibility'
    | '/wheel'
    | '/beaniary/met'
    | '/beans/$id'
    | '/flavours/$id'
    | '/forms/$id'
    | '/zodiacs/$id'
    | '/beaniary'
    | '/beans'
    | '/flavours'
    | '/forms'
    | '/zodiacs'
    | '/beaniary/beans/$id'
    | '/beaniary/flavours/$id'
    | '/beaniary/forms/$id'
    | '/beaniary/beans'
    | '/beaniary/flavours'
    | '/beaniary/forms'
  id:
    | '__root__'
    | '/'
    | '/beanstalk'
    | '/calendar'
    | '/compatibility'
    | '/wheel'
    | '/beaniary/met'
    | '/beans/$id'
    | '/flavours/$id'
    | '/forms/$id'
    | '/zodiacs/$id'
    | '/beaniary/'
    | '/beans/'
    | '/flavours/'
    | '/forms/'
    | '/zodiacs/'
    | '/beaniary/beans/$id'
    | '/beaniary/flavours/$id'
    | '/beaniary/forms/$id'
    | '/beaniary/beans/'
    | '/beaniary/flavours/'
    | '/beaniary/forms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeanstalkRoute: typeof BeanstalkRoute
  CalendarRoute: typeof CalendarRoute
  CompatibilityRoute: typeof CompatibilityRoute
  WheelRoute: typeof WheelRoute
  BeaniaryMetRoute: typeof BeaniaryMetRoute
  BeansIdRoute: typeof BeansIdRoute
  FlavoursIdRoute: typeof FlavoursIdRoute
  FormsIdRoute: typeof FormsIdRoute
  ZodiacsIdRoute: typeof ZodiacsIdRoute
  BeaniaryIndexRoute: typeof BeaniaryIndexRoute
  BeansIndexRoute: typeof BeansIndexRoute
  FlavoursIndexRoute: typeof FlavoursIndexRoute
  FormsIndexRoute: typeof FormsIndexRoute
  ZodiacsIndexRoute: typeof ZodiacsIndexRoute
  BeaniaryBeansIdRoute: typeof BeaniaryBeansIdRoute
  BeaniaryFlavoursIdRoute: typeof BeaniaryFlavoursIdRoute
  BeaniaryFormsIdRoute: typeof BeaniaryFormsIdRoute
  BeaniaryBeansIndexRoute: typeof BeaniaryBeansIndexRoute
  BeaniaryFlavoursIndexRoute: typeof BeaniaryFlavoursIndexRoute
  BeaniaryFormsIndexRoute: typeof BeaniaryFormsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wheel': {
      id: '/wheel'
      path: '/wheel'
      fullPath: '/wheel'
      preLoaderRoute: typeof WheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beanstalk': {
      id: '/beanstalk'
      path: '/beanstalk'
      fullPath: '/beanstalk'
      preLoaderRoute: typeof BeanstalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zodiacs/': {
      id: '/zodiacs/'
      path: '/zodiacs'
      fullPath: '/zodiacs/'
      preLoaderRoute: typeof ZodiacsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavours/': {
      id: '/flavours/'
      path: '/flavours'
      fullPath: '/flavours/'
      preLoaderRoute: typeof FlavoursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/': {
      id: '/beans/'
      path: '/beans'
      fullPath: '/beans/'
      preLoaderRoute: typeof BeansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaniary/': {
      id: '/beaniary/'
      path: '/beaniary'
      fullPath: '/beaniary/'
      preLoaderRoute: typeof BeaniaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zodiacs/$id': {
      id: '/zodiacs/$id'
      path: '/zodiacs/$id'
      fullPath: '/zodiacs/$id'
      preLoaderRoute: typeof ZodiacsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$id': {
      id: '/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof FormsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavours/$id': {
      id: '/flavours/$id'
      path: '/flavours/$id'
      fullPath: '/flavours/$id'
      preLoaderRoute: typeof FlavoursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/$id': {
      id: '/beans/$id'
      path: '/beans/$id'
      fullPath: '/beans/$id'
      preLoaderRoute: typeof BeansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaniary/met': {
      id: '/beaniary/met'
      path: '/beaniary/met'
      fullPath: '/beaniary/met'
      preLoaderRoute: typeof BeaniaryMetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaniary/forms/': {
      id: '/beaniary/forms/'
      path: '/beaniary/forms'
      fullPath: '/beaniary/forms/'
      preLoaderRoute: typeof BeaniaryFormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaniary/flavours/': {
      id: '/beaniary/flavours/'
      path: '/beaniary/flavours'
      fullPath: '/beaniary/flavours/'
      preLoaderRoute: typeof BeaniaryFlavoursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaniary/beans/': {
      id: '/beaniary/beans/'
      path: '/beaniary/beans'
      fullPath: '/beaniary/beans/'
      preLoaderRoute: typeof BeaniaryBeansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaniary/forms/$id': {
      id: '/beaniary/forms/$id'
      path: '/beaniary/forms/$id'
      fullPath: '/beaniary/forms/$id'
      preLoaderRoute: typeof BeaniaryFormsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaniary/flavours/$id': {
      id: '/beaniary/flavours/$id'
      path: '/beaniary/flavours/$id'
      fullPath: '/beaniary/flavours/$id'
      preLoaderRoute: typeof BeaniaryFlavoursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaniary/beans/$id': {
      id: '/beaniary/beans/$id'
      path: '/beaniary/beans/$id'
      fullPath: '/beaniary/beans/$id'
      preLoaderRoute: typeof BeaniaryBeansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeanstalkRoute: BeanstalkRoute,
  CalendarRoute: CalendarRoute,
  CompatibilityRoute: CompatibilityRoute,
  WheelRoute: WheelRoute,
  BeaniaryMetRoute: BeaniaryMetRoute,
  BeansIdRoute: BeansIdRoute,
  FlavoursIdRoute: FlavoursIdRoute,
  FormsIdRoute: FormsIdRoute,
  ZodiacsIdRoute: ZodiacsIdRoute,
  BeaniaryIndexRoute: BeaniaryIndexRoute,
  BeansIndexRoute: BeansIndexRoute,
  FlavoursIndexRoute: FlavoursIndexRoute,
  FormsIndexRoute: FormsIndexRoute,
  ZodiacsIndexRoute: ZodiacsIndexRoute,
  BeaniaryBeansIdRoute: BeaniaryBeansIdRoute,
  BeaniaryFlavoursIdRoute: BeaniaryFlavoursIdRoute,
  BeaniaryFormsIdRoute: BeaniaryFormsIdRoute,
  BeaniaryBeansIndexRoute: BeaniaryBeansIndexRoute,
  BeaniaryFlavoursIndexRoute: BeaniaryFlavoursIndexRoute,
  BeaniaryFormsIndexRoute: BeaniaryFormsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
